SELECT * FROM USUARIOS_RETOS;
SELECT * FROM USUARIOS_BENEFICIOS;

UPDATE [USUARIOS_EVENTOS]
SET [ASISTIO] = 0
WHERE [USUARIO] = 1;

SELECT * FROM BENEFICIOS;
SELECT * FROM RETOS;

EXEC GetUserTotalPoints @usuario_id = 1;

INSERT INTO [RETOS] ([NOMBRE], [DESCRIPCION], [PUNTAJE])
VALUES (
        'Reto de Pasos',
        'Completar 10,000 pasos diarios por una semana',
        100
    );

INSERT INTO USUARIOS_RETOS (ID_USUARIO, ID_RETO, COMPLETADO)
VALUES (1, 1, 1);
